name: Dashboards SQL Query Workbench Test & Build

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '.'
      - '.github/workflows/sql-workbench-test-build-workflow.yml'

env:
  PLUGIN_NAME: dashboards-query-workbench
  OPENSEARCH_VERSION: 'main'
  OPENSEARCH_PLUGIN_VERSION: 2.4.0.0
  ACTIONS_STEP_DEBUG: true

jobs:
  tests:
    name: Run unit tests
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      # Enable longer filenames for windows
      - name: Enable longer filenames
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true
      - name: Checkout OpenSearch Dashboards
        uses: actions/checkout@v2
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          ref: ${{ env.OPENSEARCH_DASHBOARDS_VERSION }}
          path: OpenSearch-Dashboards

      - name: Checkout workbench OpenSearch Dashboards plugin
        uses: actions/checkout@v2
        with:
          path: OpenSearch-Dashboards/plugins/dashboards-query-workbench

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './OpenSearch-Dashboards/.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Yarn
        # Need to use bash to avoid having a windows/linux specific step
        shell: bash
        run: |
          YARN_VERSION=$(node -p "require('./OpenSearch-Dashboards/package.json').engines.yarn")
          echo "Installing yarn@$YARN_VERSION"
          npm i -g yarn@$YARN_VERSION
      - run: node -v
      - run: yarn -v

      - run: pwd
      - run: ls OpenSearch-Dashboards/plugins/dashboards-query-workbench

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: OpenSearch-Dashboards/plugins/dashboards-query-workbench/node_modules
          key: ${{ runner.os }}-cache

      - name: Bootstrap plugin/opensearch-dashboards
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd OpenSearch-Dashboards/plugins/dashboards-query-workbench
          yarn osd bootstrap

      - name: Test
        if: github.event_name == 'push'
        run: |
          cd OpenSearch-Dashboards/plugins/dashboards-query-workbench
          yarn test:jest --coverage

      - name: Build Artifact
        run: |
          cd OpenSearch-Dashboards/plugins/dashboards-query-workbench
          yarn build
          mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OPENSEARCH_PLUGIN_VERSION }}.zip

      - name: TestCoverage
        if: github.event_name == 'pull_request'
        uses: joshuali925/Jest-Coverage-Diff@master
        with:
          fullCoverageDiff: true
          directory: OpenSearch-Dashboards/plugins/dashboards-query-workbench
          runCommand: "yarn test:jest --coverage --collectCoverage=true --coverageDirectory='./' --coverageReporters='json-summary'"
          delta: 0.5
          afterSwitchCommand: "yarn osd bootstrap"

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v1 # can't update to v3 because upload fails
        with:
          name: dashboards-query-workbench-${{ matrix.os }}
          path: OpenSearch-Dashboards/plugins/dashboards-query-workbench/build
